version: "3.8"
services:
  apexapp:
    build:
      context: .
      dockerfile: Docker-files/app/Dockerfile
    image: oluty/apexapp
    container_name: apexapp
    ports:
      - "3000:3000"
    env_file:
      - .env 
    environment:
      PORT: ${{ secrets.PORT }}
      DB_URL: ${{ secrets.DB_URL }}